### ISSUE TITLE
A few Issues and minor oddities [Minecolonies][Corail Recycler][Solar Generation]

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/foreshadowing#2]
For Minecolonies:

Due to Aquaculture 2, the fisherman seems incapable of catching any fish whatsoever. Additionally, the lumberjack doesn't seem to work with ferroustry trees/saplings in the lumberjack settings. Need to investigate further if it's an issue with those trees only or if the lumberjack cannot work period. Most likely the former than the latter.

Corail Recycler:
It looks like it does not recycle the pet/horse armor, of which the dungeons and chests in general give you plenty of.

Solar Generation:
While the recipes are in, the first tier of panels cannot be made because there's no recipe for it. Thus, the mod becomes useless.

**Comment by kreezxil** [comment]
weird, my fisherman was catching fish after the last update, the one you guys weren't able to play because curse wouldn't acknowledge the update, it's going 30 hours now.

Removed solar generation mod because after 28 days since someone else reported it the mod author has no intention of fixing it. His solution blame the mods he depends on, despite other mods clearly having the special ingots. https://github.com/Edivad99/SolarGeneration/issues/17 <--- I'm sure I'm going to get some hate for referencing it, but it's the reason this mod is gone from the pack.

There is currently no way for me to easily fix Corail Recycler.

Also in the future make issue into it's own issue that way the ones I can't get to can stay open.
