### ISSUE TITLE
growth accelerator recipe change

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/foreshadowing#30]
make all prosperity gemstones require a nether star to craft instead of a simple diamond.

**Comment by T0uchMeSenpai** [comment]
that kinda makes all of ma locked behind whether or not you farm the wither though.
unless you meant something else and i misunderstood.

**Comment by kreezxil** [comment]
I did mean something else.

Right now the infusion recipes appears to be variable allowing for even
lower tier infusion crystals to be used to make higher tiered infusium.
What I meant to say was limit the lower tier infusion crystal to lower tier
infusium recipes. ie, work out the logistics of that, and ensure that the
t3 infusium uses a nether star for it's infusion gem. At some point you
will get what you need to make nether star seeds and this will again become
pointless. Which means I'll need to knock out the nether star seeds. Thus
requiring a battle with the wither to make a very precious growth
accelerator.

**Comment by kreezxil** [comment]
IN EFFECT gating half of MA behind the wither.

**Comment by T0uchMeSenpai** [comment]
growth accelerators work best stacked, on their own you won't notice much of a difference, i tested this in single player. Thus there's two problems to consider:
1. Getting enough stacks to make accelerators actually feel like they speed up your farming in a meaningful way, cost aside, seem to cause lag (based on observations from my farm). Granted, my farm was an extreme case but it's relatively doable if you invest in MA enough.
2. As mentioned, because their speed only becomes noticeable when there's stacks of them, it becomes an easily passable option. No point investing in a minor speed up when you could make an extra field to farm twice as efficiently with the amount of inferium you'd need.

As far as nether star seeds go, the only reason they seem op is because you really don't need nether stars for a lot of things, so, even with one or two plants (which need a few wither kills, because nether crux is required) you end up swimming in nether stars regardless as of right now (despite them taking more than just a single harvest to make a single star). Certainly, removing the seeds completely is a way to go about it, but at the same time it feels like too much of a hard gate so to speak.

**Comment by kreezxil** [comment]
it's interesting that your constantly debating it.

The pack has everything in you need to farm the wither. so even then with my attempts to slow down MA progression you could still have quite a few growth accelerators.

The point is your farm is not a single use situation, we've seen it before on my other packs, it's a common thing to do, the fact that you went ahead and did on server for which you do not donate tells me that it is going to be a problem. If you did donate, I would still consider it a problem. In order to allow all of your 1,688 growth accelerators to function without lagging the server, and let's be brutally honest, from what we could see you were only half done with that contraption, the server would need to be on it's own i7 64gb at 3.4ghz per core minimum SSD cached dedicated and be the only account running on the system. That's where we are or were headed with just your build alone, imagine another 5 or even more players doing this.

Your farm didn't happen just because you know how to do it, it happened because the mod itself leads you into rather rapidly for those that wish to actually study the mod.

If I bring it to the attention of the mod author he will say I have crafttweaker and datapacks, do something about it. Which is what all the best packs do, they do something about it. Lock down recipes, remove recipes, gate recipes.

Instead of debating the need to keep the status quo, I would expect you to offer me alternatives that I could try in regards to gating. That would say allow someone to have 32 growth accelerators but it is some expenonentially harder to get the next one.

**that gives me an idea for a mod**, exponentially harder. Make recipes get harder over time.

**Comment by T0uchMeSenpai** [comment]
I am not debating whether MA's accelerated farming is good or bad, it's bad imho. Just, in terms of tweaks, and again, in my honest opinion, should be done in a smoother way. I do not think keeping things as they are is beneficial. At the same time, because I am not sure what exactly can be tweaked, I feel I can only give opinions. If we talk just recipes then, rather than nerfing the basic materials, tweak the tier recipes instead. Though, having only what, two bosses or so, makes the smoothing part a bit harder, if we are to go that route. Perhaps making later tiers of materials more reliant on growing a variety of stuff (essence)? I mean, there's a whole lot of essence in MA that's only used to make monster eggs. Maybe we could make use of that (eg, use overworld mob essences for, like, tier 3, nether for tier 4, enderman, nether stars and dragon egg for 5 and up? or something like that)

On the other hand, we can look at planttech's progression. While the progression there, as a curve, is undoubtedly smooth, the fact you need very specific biome borders to crossbreed certain plants  (a whole lot of them need completely opposite temperatures and you can only guarantee that currently by making a garden between a snowy biome and a desert for example)  because of environmental differences makes it feel way less rewarding, but it's the exact opposite of MA in that regard (much easier, much faster, but it's exactly that speed that makes you feel like you need to do more).

**Comment by kreezxil** [comment]
Thank the pixels, i thought you were defending a broken system.

The only way to ensure something that is workable to all is to effect a change. And then once the players are affected feedback would hopefully ensue.

I can think of an even harder gate that would require enchanted swords.

I could make the tier 1 infusion gem be absolutely replaced with a zombie/skeleton/creeper head

this would give a reason to actually do enchantment of equipment for those that can't find a reason to do it.

Tier 2 would require say and enderman head, tier 3 pig zombie and wither skeleton head, and tier 4 a nether star.

**Comment by kreezxil** [comment]
whether or not that is proverbially "smooth" or not remains to be seen; however, I would postulate that doing this would bring fun and excitement to the pack. No more sleeping through the night, because you need heads. Or lots of deep cave spelunking to get heads. Not to mention the constant need to repair and enchant gear that is capable of severing heads.

**Comment by kreezxil** [comment]
oh here is that conversation, lol, ok, w/e. so depending on how you feel about this mod, I either nerfed it or heavily rebalanced it.

It is now basically late game too as of these changes.

No more master infusion crystal unless you got one, here's hoping you and that crystal fall into the void or lava.

The basic crystal now has 100 uses instead of 1000.
And can't be made with a diamond but instead a nether star, you're going to fight the wither a lot to progress in this mod. Strongly suggest you fight it 5 times to get materials to make the nether star seeds. Happy hunting!

Also growth accelerator cool down as at 10 previously, now that is 200. So there's that too. Finally having 1,688 growth accelerators will have hardly much effect at all, even on server performance. We'll soon see. I know @T0uchMeSenpai is going to test it out.
