### ISSUE TITLE
Mod request: Thermal Dynamics

### ISSUE THREAD

**Issue by purestone9** [kreezxil/foreshadowing#33]
Just thermal dynamics from the trilogy of thermal mods
That way we have a mod in there for piping luquids and items

**Comment by kreezxil** [comment]
I saw they updated their cofh core a few days ago, when I added it everything crashed repeatedly. therefore adding that which apparently ported because you're asking. you did research it right? ... will likely cause a crash unless its the only mod in the pack. I'll investigate later once I'm sure the mods we use have update to 31.1.16 or better.

**Comment by purestone9** [comment]
ill test it real quick, i sent the request while i was at work ans wasnt able to test

**Comment by purestone9** [comment]
you know
im just gonna close this
