### ISSUE TITLE
consider adding: storage drawers

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/foreshadowing#38]
I saw the author updated the mod to 1.15.2

Sure, you can PROBABLY not have to use any storage period other than the highest tier disks if you make a decent setup (combination of ferroustry, MA (it's important to note, without growth accelerators) and extended furnaces) but storage drawers feel like a good compliment to refined storage.

**Comment by mummabia** [comment]
I second this suggestion.  ily storage draws and I'm kinda missing them.  Thanks.

**Comment by kreezxil** [comment]
I  added them when I started the pack and they caused major ill effects
back then, so unless he's update the mod for 1.15.2 tier in the last month,
i'm not adding it.

**Comment by purestone9** [comment]
It had an update Feb 23 2020
This is the change log

- Fixed recipe load errors
- Fixed slots still holding item if count is 0 and drawer is then unlocked
- Fixed crash when breaking drawers when certain mods are interacting with them
- Fixed trim, controller, and slave blocks not dropping when broken
- Fixed identical broken drawers not able to stack
- Fixed upgrades not able to be applied by right-clicking drawers
- Fixed compacting drawers containing items having wrong visual slots when placed back in world
- Fixed drawer recipes to only accept wooden chests
- Changed template recipe to give 4 items instead of 2
- Added illumination upgrade, which significantly brightens labels

They also updated the 16th and 18th

- Fix rendering crash in MC 1.15.0 and 1.15.1

**Comment by kreezxil** [comment]
hopefully good enough, will give it another shot.

**Comment by kreezxil** [comment]
adding it now, if you don't see it in the release it'll be because it had a problem.
