### ISSUE TITLE
World_Blender crashed server

### ISSUE THREAD

**Issue by mummabia** [kreezxil/foreshadowing#55]
Hi, I just upgraded my server to 1.15.2-2.5.20 and found it was crashing.  Removed mod World_Blender and it was OK.  I'm not sure if it's me or the server or the mod.  I don't even know if I uploaded the log correctly to Github.  

The server is a hosted server that I am manually updating by copying up the server files.

Let me know if you need any more info.  Thanks.

[crash-2020-03-20_13.24.00-server.txt](https://github.com/mummabia/logs/blob/master/crash-2020-03-20_13.24.00-server.txt)

**Comment by kreezxil** [comment]
# you did fail to put the crash report properly on the internet.

I'll give you quick tutorial on posting on gist.


![image](https://user-images.githubusercontent.com/3880072/77166824-ee07c200-6a82-11ea-9532-08130ae57dd6.png)

Now open your file browser and drag and drop the file to the empty white space

![image](https://user-images.githubusercontent.com/3880072/77167027-3b842f00-6a83-11ea-945d-5be8fcbd5555.png)

Now click on **Create Public Gist**

![image](https://user-images.githubusercontent.com/3880072/77167280-be0cee80-6a83-11ea-9dac-a6094809c91d.png)

The top part will change after you do that.

![image](https://user-images.githubusercontent.com/3880072/77167342-ded54400-6a83-11ea-9f93-cec1af84dbe0.png)

Copy either part and paste it into the crash report tracker.

### Note
Even if you use another pasting service the steps are nearly identical

## World Blender has issue an update since this, so it's possible someone has reported the issue already.

#### also please follow the steps above and submit the crash report again, I need it to go with this one. 
https://github.com/TelepathicGrunt/WorldBlender/issues/2

Apparently other mod authors not World Blender are doing bad things.

**Comment by TelepathicGrunt** [comment]
It's more of an issue on my end due to me missing some null checking. If you download 1.2.4 of World blender which was just approved on CurseForge, this issue should be resolved! :)

**Comment by kreezxil** [comment]
ok, I was about to say that it seems like you fixed it already.

@mummabia if after todays update there remains an issue feel free to open a new issue and I'll get linked to @TelepathicGrunt

**Comment by mummabia** [comment]
Thanks guys.  I upgraded to 1.15.2-2.5.21 and it was fine.  Then rebooted and it crashed, then rebooted  again and it's once again fine.  I will log a new issue should I have any further problems.  Thanks again for being so gracious with your help.
